# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- nomatch

variables:
# Could potentially parse this from  $(Build.Repository.Name) = fhirfactory/pegacorn
#  dockerImageName: '$(Build.Repository.Name)'
  dockerImageName: 'pegacorn-communicate-push-gateway'
  projectVersion: '1.0.0-snapshot'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- bash: |
    buildTimestamp=$(TZ='Australia/Sydney' date --rfc-3339='seconds')
- task: Docker@2
  displayName: 'Build a docker image'
  inputs:
    containerRegistry: 'AetherAzureContainerRegistry'
    repository: '$(dockerImageName)'
    tags: '$(projectVersion)'
    command: 'build'
    Dockerfile: 'Dockerfile'
    arguments: '--build-arg IMAGE_BUILD_TIMESTAMP="$(buildTimestamp)"'
- task: Docker@2
  displayName: 'Push a docker image'
  inputs:
    containerRegistry: 'AetherAzureContainerRegistry'
    repository: '$(dockerImageName)'
    tags: '$(projectVersion)'
    command: 'push'
