---
apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
#      affinity:
#        nodeAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 1
#            preference:
#              matchExpressions:
#              - key: computeResources
#                operator: In
#                values:
#                - High
      initContainers:
      - env:
        - name: GCM_SECRET
          valueFrom:
           secretKeyRef:
            name: {{ .Values.serviceName }}-secrets
            key: gcmSecret
        name: init
        image: alpine:3.12.3
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        command: 
          - sh
          - "-c"
          - "echo Updating /var/lib/sygnal/config/sygnal.yaml file;
            [ -e /var/lib/sygnal/config/sygnal-with-placeholders.yaml ] || cp /var/lib/sygnal/config/sygnal.yaml /var/lib/sygnal/config/sygnal-with-placeholders.yaml;
            /bin/cp -f /var/lib/sygnal/config/sygnal-with-placeholders.yaml /var/lib/sygnal/config/sygnal.yaml;
        {{- if (.Values.externalDnsEntry) }} 
            sed -i \"s/pegacorn-communicate-push-gateway.site-a/{{ .Values.externalDnsEntry }}/\" /var/lib/sygnal/config/sygnal.yaml;
        {{- end }}
            sed -i 's/INFO/{{ .Values.matrixLogLevel | default "INFO" }}/' /var/lib/sygnal/config/sygnal.yaml;
            sed -i \"/#  type: gcm/ a\\    api_key: ${GCM_SECRET} \" /var/lib/sygnal/config/sygnal.yaml;
            sed -i '/#  type: gcm/ a\\    type: gcm ' /var/lib/sygnal/config/sygnal.yaml;
            sed -i '/#  type: gcm/ a\\  {{ .Values.androidAppId }}: ' /var/lib/sygnal/config/sygnal.yaml;
            echo START of /var/lib/sygnal/config/sygnal.yaml file content;
            echo ' ';
            cat /var/lib/sygnal/config/sygnal.yaml;
            echo ' ';
            echo END of /var/lib/sygnal/config/sygnal.yaml file content;
            "
        volumeMounts:
        - name: config
          mountPath: /var/lib/sygnal/config
      containers:
      - env:
        {{- if (.Values.httpProxyHostAndPort) }} 
        - name: HTTPS_PROXY
          value: http://{{ .Values.httpProxyHostAndPort }}
        {{- end }}
        - name: SYGNAL_CONF
          value: /var/lib/sygnal/config/sygnal.yaml
        {{- if (.Values.dnsEntry) }} 
        - name: DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        {{- end }}
        {{- if (.Values.externalDnsEntry) }} 
        - name: EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        {{- end }}
        - name: KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE_TIME
          value: "{{ date "20060102-150405" .Release.Time }}"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: JVM_MAX_HEAP_SIZE
          value: "{{ .Values.jvmMaxHeapSizeMB }}m"
        # Set the minimum memory that will be available on the node to assign to the container to be the jvmMaxHeapSizeMB plus 128 MB 
        # for the native heap and operation system processes associated with running Java
        # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#motivation-for-memory-requests-and-limits
        # and https://www.alibabacloud.com/blog/kubernetes-demystified-restrictions-on-java-application-resources_594108
        resources:
          requests:
            memory: "{{ (add 128 .Values.jvmMaxHeapSizeMB) | default 2048 }}Mi"
        image: {{ .Values.dockerRepo }}pegacorn-communicate-push-gateway:{{ .Values.imageTag }}            
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 30
        name: sygnal
        ports:
        - containerPort: 5000
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 10
        securityContext:
          privileged: false
        volumeMounts:
        - name: config
          mountPath: /var/lib/sygnal/config
        - name: certificates
          mountPath: /var/lib/sygnal/certificates
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      volumes:
      - name: config
        hostPath: 
          path: {{ .Values.hostPath }}
      - name: certificates
        hostPath:
          path: {{ .Values.hostPathCerts }}